language: python
# python:
#   - "2.7"

services:
  - docker

before_script:
  - docker pull sslhep/servicex-transformer:rabbitmq || true

script:
  - docker build --cache-from sslhep/servicex-transformer:rabbitmq -t sslhep/servicex-transformer:${TRAVIS_BRANCH} .
  - docker run sslhep/servicex-transformer:${TRAVIS_BRANCH} bash -c "source /home/atlas/.bashrc && flake8"
  - docker run -e "CODECOV_TOKEN=$CODECOV_TOKEN" sslhep/servicex-transformer:${TRAVIS_BRANCH} bash -c "source /home/atlas/.bashrc &&  coverage run -m pytest -v; codecov"

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
deploy:
  provider: script
  script: docker push sslhep/servicex-transformer:${TRAVIS_BRANCH}
  on:
      all_branches: true
