ARG BASE_VERSION=latest

FROM sslhep/servicex-transformer-base:${BASE_VERSION}
COPY requirements.txt .
RUN /bin/bash -c "source /home/atlas/release_setup.sh && \
    pip install --user -r requirements.txt"

COPY . .
RUN mv uproot_transformer.py xaod_branches.py && \
    mv validate_uproot_request.py validate_requests.py



